### ISSUE TITLE
Protocol

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/antibody-and-antiviral-deployment#50]
I have just realised that we previously written a prose protocol version for this study as opposed to the analytic code version that is openly shared by default.

As we have virtually completed it we should tidy up and share

Its available in the gdoc. We can share on the repo but we should also consider depositing with an appropriate registry and getting a DOI for future reference (list below from NIHR website - I'm not sure which is best one for this)

https://docs.google.com/document/d/1a8MRjel5qkEtOSf3ljWaI4cUTxoyKD9AfESINFAT8AE/edit#

1.	ISRCTN is an international database and endorsed by WHO, ICMJE AND HRA
2.	EudraCT/ EU Clinical Trials Register (EU-CTR)- endorsed by WHO, ICMJE and HRA
3.	Clinical [trials.gov](http://trials.gov/) – endorsed by ICMJE and HRA
4.	The Research Registry – endorsed by HRA and accept a wide variety of studies
5.	PROSPERO - required for any evidence synthesis research

**Comment by brianmackenna** [comment]
@alexwalkerepi has also suggested OpenScience framework might be an option

**Comment by wjchulme** [comment]
My vote would be OSF because 

a) it's not built for clinical trials
b) it has big community buy-in and is likely to persist (trials.gov was down during Trump's US govt shutdown)
c) it's transparently funded
d) it has good integration with git, if needed

**Comment by LindaNab** [comment]
We've tidied the protocol and added a table to the protocol describing 3 protocol changes accompanied with reasons why we've deviated from the protocol there.
Protocol has been uploaded as part of a Project to the Open Science Framework, doi: doi.org/10.17605/OSF.IO/SFPBA.
